# Generated by Django 4.1.7 on 2023-06-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_remove_lesson_author_remove_lesson_tags_delete_tag'),
        ('courses', '0003_alter_course_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson', verbose_name='Уроки'),
        ),
    ]
