# Generated by Django 4.1.7 on 2023-06-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('a', 'Легкий'), ('b', 'Средний'), ('b', 'Сложный')], max_length=1, verbose_name='Уровень сложности'),
        ),
    ]
