# Generated by Django 4.1.7 on 2023-06-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_lesson'),
        ('lesson', '0003_remove_lesson_author_remove_lesson_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Уроки'),
        ),
    ]
