# Generated by Django 4.1.7 on 2023-07-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_lesson'),
        ('lesson', '0004_lesson_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курсы'),
        ),
    ]
