# Generated by Django 4.1.7 on 2023-07-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_alter_lesson_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='words',
            new_name='redy_words',
        ),
        migrations.AddField(
            model_name='lesson',
            name='word_eng',
            field=models.CharField(default=1, max_length=75, verbose_name='Термин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='word_rus',
            field=models.CharField(default=1, max_length=75, verbose_name='Определение'),
            preserve_default=False,
        ),
    ]
