# Generated by Django 4.1.7 on 2023-04-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrongcards',
            name='error_text',
            field=models.TextField(verbose_name='Подробнее об ошибки'),
        ),
        migrations.AlterField(
            model_name='wrongcards',
            name='mistake_in',
            field=models.CharField(choices=[(None, 'Выберите в чем ошибка'), ('a', 'терминe'), ('b', 'определение'), ('c', 'произношение')], max_length=3, verbose_name='Ошибка в'),
        ),
    ]
