# Generated by Django 4.1.7 on 2023-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_image_alter_card_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='photo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='related_words',
            field=models.TextField(blank=True, verbose_name='Связанные слова'),
        ),
    ]
